name: 02 - Workflow Events

on:
  pull_request:
  schedule:
   - cron: '*/5 * * * *'
  workflow_dispatch:


jobs:
   Echo-event-trigger:
      runs-on: ubuntu-latest
      steps:
         - name: Show the event-trigger
           run: echo "It's been triggered by ${{github.event_name}} event!"