name: 03 - Workflow Runners

on: push

jobs:
  echo-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Show Ubuntu
        run: |
          echo "This job runs on an Ubuntu runner"
          echo "Runner-OS: $RUNNER_OS"
  echo-mac:
    runs-on: macos-latest
    steps:
      - name: Show macos
        run: |
          echo "This job runs on a MacOS runner"
          echo "Runner-OS: $RUNNER_OS"
  echo-windows:
    runs-on: windows-latest
    steps:
      - name: Show Windows
        shell: bash
        run: |
          echo "This job runs on a Windows runner"
          echo "Runner-OS: $RUNNER_OS"