name: 03 - Workflow Runners

on: push

jobs:
  echo-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: echo ubuntu
        run: |
          echo "This job runs on on an Ubuntu runner"
          echo "Runner-OS: $RUNNER_OS"