name: 04 - Using Actions

on: workflow_dispatch

# 1. Checkout Code
# 2. Install Node
#Â 3. Install dependencies
# 4. Execute automated tests
jobs:
   build:
      runs-on: ubuntu-latest
      defaults:
          run:
           working-directory: apps/react-app

      steps:
         - name: Checkout Code
           uses: actions/checkout@v4
         - name: Print Folders/Files
           run: ls
         - name: Setup Node
           uses: actions/setup-node@v4
           with:
            node-version: '20.x'
         - name: Install Dependencies
           run: npm ci
         - name: Run Unit Tests
           run: npm run test